version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --hostname-strict=false
      - --proxy=edge
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - keycloak